### ISSUE TITLE
Issues uploading data to ElasticSearch.

### ISSUE THREAD

**Issue by JosephAMumford** [amazon-connect/amazon-connect-call-quality-monitoring#4]
Hi,

I have deployed this solution twice in the past few days and getting the same errors with ElasticSearch.  I noticed in the monitoring CCP I was getting a CORS error when sending the 'softphonecallreport'.  The Lambda that handles this API call was failing with the following error:

`[ERROR] RequestError: RequestError(400, 'illegal_argument_exception', 'field [report] not present as part of path [report.callStartTime]')
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 26, in lambda_handler
    es.index(index='softphonecallreport-', doc_type='document', body=body, pipeline="reports_dailyindex")
  File "/opt/python/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/python/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 407, in index
    body=body,
  File "/opt/python/lib/python3.7/site-packages/elasticsearch/transport.py", line 362, in perform_request
    timeout=timeout,
  File "/opt/python/lib/python3.7/site-packages/elasticsearch/connection/http_requests.py", line 173, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/python/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 244, in _raise_error
    status_code, error_message, additional_info`

The event from the CCP looks correct, it's just failing at the point where it uploads the document to ElasticSearch.  

I'm also getting issues with `softphonestreamstats` and `apimetrics.`  Both of these document types are getting written to the `softphonestreamstats` index only.  My `apimetrics` and `softphonecallreport` indices are empty.

Thanks

**Comment by kqia040** [comment]
Hey Joseph thanks for reaching out. We're aware of this issue. Planning to release a fix by the end of month

**Comment by taylor-zr** [comment]
Hey Joseph! The release has been deployed. Please give it a shot and let us know if you run into any issues.

**Comment by JosephAMumford** [comment]
Thanks, I'll check it out!
